### ISSUE TITLE
Move to ASP.NET Security repo

### ISSUE THREAD

**Issue by leastprivilege** [blowdart/idunno.Authentication#11]
this should be part of the product IMO

**Comment by blowdart** [comment]
You know there's no way in hell I'm going to let basic authentication get shipped with the product. Certificate, if I get enough decent tests maybe.

**Comment by leastprivilege** [comment]
I was talking about certs. Not basic auth.

**Comment by blowdart** [comment]
It's happening, poor @hoak is going to do it.

**Comment by leastprivilege** [comment]
yay ;)

**Comment by abatishchev** [comment]
Can you point to an issue in the aspnet repo where this is happening?

**Comment by blowdart** [comment]
No

**Comment by abatishchev** [comment]
Why to close this one then?

**Comment by blowdart** [comment]
I didn't. Dominick did, because, presumably he trusts me when I said it's happening. 

You can track https://github.com/aspnet/AspNetCore/issues/4663 though.
