### ISSUE TITLE
How can I inject dependencies into event callbacks

### ISSUE THREAD

**Issue by tugberkugurlu** [blowdart/idunno.Authentication#12]
Hi 👋 

> ⚠️ I am not trying to use basic auth 😄 Just using this as an example.

How can I inject dependency from the `IServiceCollection` into the events callback? This is the line: https://github.com/blowdart/idunno.Authentication/blob/1612a649a26367c0cce476aa224f9979ce0295d1/src/idunno.Authentication.Demo/Startup.cs#L23

**Comment by blowdart** [comment]
In 2.0 the Events class itself can be registered in DI as the type & implementation or you can also get the DI container via `context.HttpContext.RequestServices`.

But you know you're a horrible person for doing this :)

**Comment by blowdart** [comment]
Does this answer your question @tugberkugurlu?

**Comment by blowdart** [comment]
Closing due to lack of response.

Please reopen if you have further comments or questions on this issue.
