### ISSUE TITLE
Support net8.0 framework

### ISSUE THREAD

**Issue by Orbling** [blowdart/idunno.Authentication#145]
**Is your feature request related to a problem?**
.Net 7 is now past EOL and this library is still well used by the community, upgrading a project to .Net 8, this library was unsupported and that's a problem.

**Describe the feature you would like**
Add net8.0 to target frameworks, I do not know of any reason it would no longer work or need any extensive modification.

**Additional context**
n/a

**Comment by blowdart** [comment]
You don't need a specific .NET version, the package as is works just fine (as there have been no api changes to auth handlers for an absolute age).

Are you actually getting any errors?

**Comment by Orbling** [comment]
I had expected it to work as-is, as, as you say, there were no major changes that effected it.  NuGet just seemed to report it as missing, presumably as the framework was not a specified target.  I only use the Basic auth module for very low security dev site walls from the general public, but it's been very useful for that.  I've observed your amending commits, thank you for getting on this so blisteringly quickly, highly appreciated!  I'm not well acquainted with the NuGet system, but it has starting working since you have made those commits, as I tested it again just now.  Though I would've thought it worked off the releases rather than the active repository and you've not yet made a new release, so I have no idea what changed, as it was entirely obstinate last night.  Nevertheless your changes coming through look like sensible alterations for the interim changes to the framework, so are much appreciated.

**Comment by blowdart** [comment]
How annoyingly weird. I was going to ask you to give the new build a test, thank you for beating me to it! It's been a while since I built this via CI, let alone signed it, so I'll try to get it going within the next couple of days (I have a bunch of stuff I have booked this weekend).

**Comment by blowdart** [comment]
Fixed by https://github.com/blowdart/idunno.Authentication/commit/9d9773a0fea8a8913089ff4795db8a27a844bb38

**Comment by blowdart** [comment]
All done, and public on nuget now as v2.4.0

**Comment by Orbling** [comment]
Many thanks, sorry was away for the weekend - I very much appreciate your work on this.
