### ISSUE TITLE
Demo working but Nuget doesn't working

### ISSUE THREAD

**Issue by DomZZ** [blowdart/idunno.Authentication#15]
Hi,

I have some problems with the nuget package (.Net Core 2.0.3),
AddBasic Method is not found in Microsoft.AspNetCore.Authentication namespace.

Then since you added a demo in your code I've downloaded it and seen that everything is ok.
Finally, I've removed project reference to dunno.authentication and added the nuget package instead and I'm able to reproduce the issue.

Can you help me ?
Thanks

**Comment by blowdart** [comment]
I haven't gotten around to producing the nuget packages yet. The branch you see them mentioned them is a Work in Progress branch. Once I have some time to setup code signing, nuget will then be next. You can keep an eye on progress in https://github.com/blowdart/idunno.Authentication/issues/14

**Comment by DomZZ** [comment]
Thanks for your quick reply, I will embed your code as a project reference in the meantime.

**Comment by blowdart** [comment]
@DomZZ and now its finally on nuget, because I got over my self loathing at encouraging basic auth :)
