### ISSUE TITLE
Hello, there is WSTRUST / STS support ?

### ISSUE THREAD

**Issue by Mahe85** [blowdart/idunno.Authentication#26]
**Is your feature request related to a problem?**

**Describe the feature you would like**

**Additional context**

**Comment by blowdart** [comment]
No. There's an official WS-Fed package in Core 2.1

**Comment by Mahe85** [comment]
Thanks for your feedback! 
There is another way to do this in .net core please:
 else
            {
                binding.Security.Message.ClientCredentialType = MessageCredentialType.UserName;
                ep = new EndpointAddress("https://abc.com/adfs/services/trust/13/usernamemixed");                    
            }
            factory = new WSTrustChannelFactory(binding, ep);
            factory.TrustVersion = TrustVersion.WSTrust13;

                factory.Credentials.Windows.ClientCredential = CredentialCache.DefaultNetworkCredentials;                     


            var rst = new RequestSecurityToken
            {
                RequestType = RequestTypes.Issue,
                AppliesTo = new EndpointReference("urn:adfsmonitor"),
                KeyType = KeyTypes.Bearer,
            };
            IWSTrustChannelContract channel = factory.CreateChannel();
            GenericXmlSecurityToken genericToken = channel.Issue(rst)
             as GenericXmlSecurityToken;
            return genericToken.TokenXml.InnerXml.ToString();

**Comment by blowdart** [comment]
Now you're into WCF which is a much wider concern. You should talk to the[ WCF on Core](https://github.com/dotnet/wcf) people.
