### ISSUE TITLE
[Basic] Support for custom schema names

### ISSUE THREAD

**Issue by ig-sinicyn** [blowdart/idunno.Authentication#33]
Version used: idunno.Authentication.Basic v2.1.1.

Current implementation of `BasicAuthenticationHandler` [hardcodes 'Basic' schema name](https://github.com/blowdart/idunno.Authentication/blob/master/src/idunno.Authentication.Basic/BasicAuthenticationHandler.cs#L56-L61). 
Please, replace it with the schema name passed to `.AddBasic()`, or with value from `BasicAuthenticationOptions`.

Use case: support for custom chemas such as "Authorization: MySchema {base64credentials}"

P.S. Yep, every time someone uses basic, god kills a kitten. We're going to save cat population, but first we had to port a lot of legacy code without breaking anything:)

**Comment by blowdart** [comment]
It's already [there](https://github.com/blowdart/idunno.Authentication/blob/master/src/idunno.Authentication.Basic/BasicAuthenticationExtensions.cs#L19)

```c#
public static AuthenticationBuilder AddBasic(this AuthenticationBuilder builder, string authenticationScheme)
```

**Comment by ig-sinicyn** [comment]
It does not work with custom schema names. Just checked with
```cs
	var authHeader = context.Request.Headers[HeaderNames.Authorization].FirstOrDefault();
	logger.Trace($"Auth: {authHeader}"); // MySchema aaa....

	var result = await context.AuthenticateAsync("MySchema");
	logger.Trace($"Passed: {result.Succeeded}"); // false
	logger.Trace($"IsNone: {result.None}"); // true
```
And [here's](https://github.com/blowdart/idunno.Authentication/blob/master/src/idunno.Authentication.Basic/BasicAuthenticationHandler.cs#L56-L61) why
```cs
        private const string _Scheme = "Basic";

        // ...

            string authorizationHeader = Request.Headers["Authorization"];
            // (1)
            if (!authorizationHeader.StartsWith(_Scheme + ' ', StringComparison.OrdinalIgnoreCase))
            {
                return AuthenticateResult.NoResult();
            }

            string encodedCredentials = authorizationHeader.Substring(_Scheme.Length).Trim();
```
Check at (1) denies any auth header that does not start with "Basic"

**Comment by blowdart** [comment]
Oh scheme names in the header. Then no, this follows the RFC for basic authentication and nothing more. I'm not going to veer off from the standard.

**Comment by ig-sinicyn** [comment]
Ok, thanks.
