### ISSUE TITLE
Authentication Result is (Result.Fail), but proceed to next middleware

### ISSUE THREAD

**Issue by nadeemkhoury** [blowdart/idunno.Authentication#34]
Hi, I used certificate authentication, however, I setup the Program.cs and Startup.cs as explained in the documentation. For some reason, when the certificate validation failed, the next middleware such as MVC gets called. How can I stop the pipeline from proceeding since the authentication has failed ? 
Do you have any hookup to call when the client certificate validation is failed ? 

I made sure that `app.UseAuthentication()` is before `app.UseMvc()`. 

Any suggestion or explanation would be much appreciated.

**Comment by blowdart** [comment]
You don't, you can't. That's not how asp.net works. In fact even if it fails it won't matter until an authorize call is encountered.

**Comment by nadeemkhoury** [comment]
Thank you for quick response. I just want to escape the pipeline before it hits the MVC middleware. I will see if I would use the authorization filter, or I could write my own middleware to check if the certificate failed, I could return a unauthorizated or forbidden response immediately before it reach the authorization filter.
