### ISSUE TITLE
CertificateAuthenticationEvents is not executed when doing a request to the server

### ISSUE THREAD

**Issue by PresidentCamacho** [blowdart/idunno.Authentication#35]
**Description of the problem you are seeing**
I'm doing a request to the controller with the attribute: 
`[Authorize(AuthenticationSchemes = CertificateAuthenticationDefaults.AuthenticationScheme)]` with a client certificate

**What do you think should be happening?**
I should be entering the event: `OnValidateCertificate`

**What is actually happening?**
The event `OnValidateCertificate` is not executed and I immidiatly get 403 Forbidden returned

**My ConfigureServices() code**

```
        public static void AddClientCertificateAuthentication(this IServiceCollection services)
        {
                services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme)
                    .AddCertificate(options =>
                    {
                        options.RevocationMode = X509RevocationMode.NoCheck;
                        options.RevocationFlag = X509RevocationFlag.ExcludeRoot;
                        options.AllowedCertificateTypes = CertificateTypes.All;
                        options.ValidateCertificateUse = false;
                        options.ValidateValidityPeriod = false;
                        options.Events = new CertificateAuthenticationEvents
                        {
                            OnValidateCertificate = (context) =>
                            {
                                var validationService = context.HttpContext.RequestServices.GetService<ICertificateValidationService>();
                                if (validationService.ValidateCertificate(context.ClientCertificate))
                                {
                                    context.Success();
                                }
                                else
                                    context.Fail("Certificate invalid.");

                                return Task.CompletedTask;
                            },
                            OnAuthenticationFailed = (context) =>
                            {
                                return Task.CompletedTask;
                            }
                        };                    
                );
            }
        }

`app.UseAuthentication()` is also located in `Configure`

**Comment by blowdart** [comment]
Do you have an Authorize attribute on your endpoints? No authentication runs until it reaches an authorize?

**Comment by PresidentCamacho** [comment]
Yes I've `[Authorize(AuthenticationSchemes = CertificateAuthenticationDefaults.AuthenticationScheme)] `attribute on the controller I'm using for testing.

**Comment by blowdart** [comment]
Are you hosting under IIS, or is it directly exposed Kestrel?

**Comment by PresidentCamacho** [comment]
And I can also see in application insights that the scheme is challenged:
`AuthenticationScheme: Certificate was challenged.`

I've set up that kestrel is using client-certificate like in the readme. But it seems like it doesn't work.

```
                .UseKestrel(options =>
                {
                    options.Listen(IPAddress.Loopback, 44359, listenOptions =>
                    {
                        listenOptions.UseHttps(new HttpsConnectionAdapterOptions
                        {
                            ServerCertificate = new X509Certificate2("test.pfx", "qweasd"),
                            ClientCertificateMode = ClientCertificateMode.RequireCertificate,
                            ClientCertificateValidation = CertificateValidator.DisableChannelValidation
                        });
                    });
                })
```

I've set up my project to use ssl. So it will host it in iis express with the port 44359

**Comment by blowdart** [comment]
Can you try it with just kestrel direct? I don't believe IIS Express does cert auth. 
 
In the dropdown beside the run button pull it down and switch to the project name, rather than IIS

**Comment by PresidentCamacho** [comment]
Oh, getting some useful errors now. Not at the authentication stack though. Will get back to you. Thanks!

**Comment by PresidentCamacho** [comment]
I'm now getting 'No authentication handler is registered for the scheme 'Certificate'. The registered schemes are: ..... Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Certificate",...)?'
Should the ConfigureService part of `AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme)` come in a specific order?

Also redid my code to this:

```
                services.AddAuthentication()
                    .AddCertificate(CertificateAuthenticationDefaults.AuthenticationScheme, options =>
```

**Comment by blowdart** [comment]
If it's the only auth type just try a plain [Authorize] attribute without specifying a scheme.

**Comment by PresidentCamacho** [comment]
Seems like when switching profile I had forgot that I don't have a environment_variable I need to load the authenticationscheme Certificate. Now its complaning about having not having the right certificate so I'm on the right track. Thanks!

**Comment by blowdart** [comment]
You're welcome Mr President :)

**Comment by PresidentCamacho** [comment]
Working now :)
