### ISSUE TITLE
AuthenticationFailed event not called on invalid credentials

### ISSUE THREAD

**Issue by avalara-stephen-hickey** [blowdart/idunno.Authentication#38]
**Description of the problem you are seeing**

The `AuthenticationFailed` event is not called when the credentials are not valid.

**What do you think should be happening?**

The `AuthenticationFailed` event should be called if `(On)ValidateCredentials` sets `context.Result` to a failed `AuthenticateResult`. Arguably, it should be called if `context.Result` is not set to a successful `AuthenticateResult` (although I'm not sure what the purpose of `NoResult` is at this point in the process, which seems to be the default behavior from the example).

**What is actually happening?**

The `AuthenticationFailed` event is never fired.

**My ConfigureServices() code**

```
services.AddAuthentication(BasicAuthenticationDefaults.AuthenticationScheme)
    .AddBasic(options =>
    {
        options.Realm = "afc";
        options.AllowInsecureProtocol = _hostingEnvironment.IsDevelopment();
        options.Events = new BasicAuthenticationEvents
        {
            OnValidateCredentials = async context =>
            {
                if (context.Username == context.Password)
                {
                    var claims = new[]
                    {
                        new Claim(ClaimTypes.NameIdentifier,
                            context.Username,
                            ClaimValueTypes.String,
                            context.Options.ClaimsIssuer),
                        new Claim(ClaimTypes.Name,
                            context.Username,
                            ClaimValueTypes.String,
                            context.Options.ClaimsIssuer)
                    };

                    context.Principal =
                        new ClaimsPrincipal(new ClaimsIdentity(claims, context.Scheme.Name));

                    context.Success();

                    await Task.CompletedTask;
                }
                else
                {
                    context.Fail("Invalid credentials.");
                }
            },
            OnAuthenticationFailed = context =>
            {
                Console.WriteLine("I should see this!!!");
                return Task.CompletedTask;
            }
        };
    });

services.AddMvcCore()
    .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
    .AddAuthorization()
    .AddJsonFormatters();
```

**Steps to reproduce**

Send a request to a protected endpoint with invalid credentials (username != password)

**Comment by blowdart** [comment]
The failed event isn't for authentication failures, but rather for "Something went horrible wrong and I threw an exception". Context.Fail() doesn't count in this regard.

This behaviour mirrors the official "inbox" auth handlers, so if you want it to do as you expected you'd have to change the stack behaviour first.

**Comment by avalara-stephen-hickey** [comment]
Thank you for the explanation! Another basic auth handler I found was returning failures from invalid creds and that _seemed_ like the desired behavior but I would definitely prefer to follow the patterns of official handlers.

**Comment by blowdart** [comment]
As I leave validation up to you in the delegate you're able to capture the failures yourself in whatever logging mechanism you prefer, so yea, I want to match the more official handlers :)
