### ISSUE TITLE
System.InvalidOperationException at idunno.Authentication.Basic.BasicAuthenticationHandler.HandleChallengeAsync

### ISSUE THREAD

**Issue by rimonhanna** [blowdart/idunno.Authentication#39]
**Description of the problem you are seeing**

System.InvalidOperationException

**What do you think should be happening?**

Synchronous operations are disallowed. Call WriteAsync instead of Write.

**What is actually happening?**

App is throwing a System.InvalidOperationException at idunno.Authentication.Basic.BasicAuthenticationHandler.HandleChallengeAsync

**My ConfigureServices() code**
Irrelevant I think a the authentication is working fine, but the exception is causing a 500 error on my server every few minutes due to referencing Response.Body.Write in HandleChallengeAsync instead of Response.Body.WriteAsync which is a requirement in .Net Core 3.0

**Steps to reproduce**

Deploy any project using both certificate auth and basic auth libraries on Azure targeting .Net Core 3.0 while enabling insights and you'll get the exception

**Comment by blowdart** [comment]
Cert auth isn't targeted at 3.0, because it's now [built in](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1).  Please use the official package and if you still have problems [log an issue](https://github.com/aspnet/AspNetCore/issues).
