### ISSUE TITLE
.net core 3.1 support

### ISSUE THREAD

**Issue by PresidentCamacho** [blowdart/idunno.Authentication#41]
Hi,

Any future feature to support .net core 3.1 ? :)

**Comment by PresidentCamacho** [comment]
Saw that .net core 3.1 has Microsoft.AspNetCore.Authentication.Certificate is it similar to this package?

**Comment by blowdart** [comment]
Yes, it's almost the same (it came from here originally), so no, there will not be a package targeting 3.0, please use the inbox one.
