### ISSUE TITLE
Produce 3.0 and 3.1 packages for basic auth

### ISSUE THREAD

**Issue by blowdart** [blowdart/idunno.Authentication#46]
From @yang-er's pull request.

- [x] Update appveyor script
- [x] Check nuget package contains all three targets

**Comment by blowdart** [comment]
@yang-er I updated the appveyor environment to VS2019 to get both Core 3.0 and 3.1 installer and the packages have been produced. Do you want to see if those work for you? You can grab pre-release packages from the [current appveyor build](https://ci.appveyor.com/project/blowdart/idunno-authentication) for master.

**Comment by yang-er** [comment]
It works well! Thanks.

**Comment by blowdart** [comment]
Oh good. 

I want to address some performance issues in cert auth if I can this week, so expect a supported package towards the end of the week.

**Comment by fagnercarvalho** [comment]
I'm seeing in the README that only version 2.2.2 targets .NET Core 3.1 but I don't see 2.2.2 in NuGet, only 2.2.1. Is 2.2.1 supposed to support 3.1 or not? I'm getting HTTP 421 when running 2.2.1 in 3.1.

**Comment by blowdart** [comment]
That’s because master is the branch under development. You can take the current build assets to test it but it won’t be out until I do some work on certificate auth.

________________________________

**Comment by fagnercarvalho** [comment]
Got it, thank you for the fast reply!

**Comment by blowdart** [comment]
Fixed as in https://github.com/blowdart/idunno.Authentication/commit/c09e90f21adeb8957c3c42abd1ad5f86c433803d

Released as part of https://github.com/blowdart/idunno.Authentication/releases/tag/v2.2.2

**Comment by blowdart** [comment]
@fagnercarvalho @yang-er these should now be available on nuget for you; https://www.nuget.org/packages/idunno.Authentication.Basic/
